server:
  port: 8089
spring:
  application:
    name: springboot_cache
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03
    username: root
    password: root
mybatis-plus:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


